### ISSUE TITLE
500 Error: Failed to lookup view "index"

### ISSUE THREAD

**Issue by killfish** [zappan/node-marionette-boilerplate#1] opened 2013-04-08 18:58 UTC
I have the server up and running but I'm getting an error when trying to run the application.

Here is the stack.

Express
500 Error: Failed to lookup view "index"
at Function.app.render (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/application.js:492:17)
at ServerResponse.res.render (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/response.js:755:7)
at Function.renderAppShell (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/src/router.js:20:7)
at index (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/src/routes/home.js:12:7)
at callbacks (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/router/index.js:161:37)
at param (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/router/index.js:135:11)
at pass (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/router/index.js:142:5)
at Router._dispatch (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/router/index.js:170:5)
at Object.router (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/lib/router/index.js:33:10)
at next (/Users/cmackenz/WebstormProjects/HomeDepot/digintowin/server/node_modules/express/node_modules/connect/lib/proto.js:190:15)

**Comment by zappan** [comment] 2013-04-08 19:27
Hi there

I'm sorry, I haven't managed to write a proper Readme yet on how to run things. Let me try briefly here - some steps need to be done to have the app serving the homepage:

1) from the project root run => npm install
2) from the /server also run => npm install
3) then, to build the app, run => grunt

Starting the app server now should serve the app. Let me know if that worked for you please.

Notes: Steps 1 and 2 install dev dependencies and application dependencies, respecitvely. Step 3 builds backbone/marionette app into the public directory of the server-side app so those assets can be served. There are three different grunt builds - 'grunt dev' (alias 'grunt'), 'grunt debug' and 'grunt release' - dev serves plain client-side js files to browser, debug concatenates client-side js, release minifies on top of it.

**Comment by killfish** [comment] 2013-04-08 19:45
That almost works :) I had to modify the app.js file to point to the correct view location.

(line 49) app.set('views', publicPath + '/client');

Is that a bug or did I miss something while setting this up?

**Comment by zappan** [comment] 2013-04-11 15:17
I'm not sure why you had to modify that path. I've just tried it out and works correctly as is. From what I see, you're on Mac - if I get my hands on one through some friend, I might try to pull and run from it, but should not make a difference.

You can start server from the project root by typing ./devserver, or npm start, or going to /server and typing node server. I've tried all 3 ways and it's working as expected (Linux). If you find any additional clue - feel free to share.

I'll close the issue as I'm unable to reproduce, and you seem to have found a workaround that works for you - after all this is a boilerplate to be modified to each one's needs...

**Closed as completed by zappan** 2013-04-11 15:17 UTC
